apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zda06rrra-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zda06rrra-nodejs 
  name: zda06rrra-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: zda06rrra-nodejs 
